updated logging

diff --git a/zfsync b/zfsync
--- a/zfsync
+++ b/zfsync
@@ -30,10 +30,9 @@ readonly SNAPPREFIX="${SNAPPREFIX:-"zfsync_"}" # prefix for snapshot name
 readonly DATECMD="${DATECMD:-"date -u +%F_%H-%M-%S_UTC"}" # command to generate snapshot name timestamp
 if [ -z "${BUFFER:-}" ]; then
   if command -v mbuffer >/dev/null; then
-    readonly BUFFER="$(command -v mbuffer) -s 128k -q"
+    readonly BUFFER="$(command -v mbuffer) -s 128k"
   else
-    warn 'mbuffer executable not found'
-    readonly BUFFER="$(command -v cat)"
+    fatal 'mbuffer executable not found'
   fi
 fi
 
@@ -117,13 +116,13 @@ create_remote() {
   local -r SOURCE="$1"
   local -r FIRST=$($ZFS list -t snap -Ho name -s creation "${SOURCE}" \
     | head -n 1)
-  $ZFS send -DLcew "${FIRST}" | $BUFFER | $RPC receive -s "${SOURCE}"
+  $ZFS send -DLcew "${FIRST}" | $BUFFER -q | $RPC receive -s "${SOURCE}"
 }
 
 resume_remote() {
   local -r SOURCE="$1"
   local -r TOKEN="$2"
-  $ZFS send -e -t "${TOKEN}" | $BUFFER | $RPC receive -s "${SOURCE}"
+  $ZFS send -e -t "${TOKEN}" | $BUFFER -q | $RPC receive -s "${SOURCE}"
 }
 
 update_remote() {
@@ -137,7 +136,7 @@ update_remote() {
     | awk "\$2 == ${REMOTEGUID} { print \$1 }")"
   [ -n "${STARTSNAP}" ] || fatal "can't find snapshot/bookmark for guid=%s" "${REMOTEGUID}"
   local -r FINISHSNAP="$($ZFS list -t snap -Ho name -S creation "${SOURCE}" | head -n 1)"
-  $ZFS send -DLcew -I "${STARTSNAP}" "${FINISHSNAP}" | $BUFFER | $RPC receive -s "${SOURCE}"
+  $ZFS send -DLcew -I "${STARTSNAP}" "${FINISHSNAP}" | $BUFFER -q | $RPC receive -s "${SOURCE}"
 }
 
 mirror() {
@@ -228,8 +227,9 @@ server() { # run from authorized_keys file on the backup server (ie. command="zf
       ;;
     'receive')
       prepare ":Penvt:Fhsuo:x:dA" "$@"
-      ${BUFFER} | $ZFS receive "${ARGS[@]}"
-      SSH_ORIGINAL_COMMAND="status ${*: -1}" server "${TARGET}";;
+      ${BUFFER} -q | $ZFS receive -v "${ARGS[@]}" >&2
+      # shellcheck disable=2124 # use last item in array as string
+      SSH_ORIGINAL_COMMAND="status ${@: -1}" server "${TARGET}";;
     'list')
       prepare ":rd:Hpo:t:s:S:" "$@"
       $ZFS list "${ARGS[@]}";;
